# Python语言程序设计（实验）——NumPy 基础教程

## Part 0. 环境安装说明

### 0.1 本地 Linux / WSL 环境安装方法（推荐）

在终端执行以下命令安装 Conda 并配置环境：

1. **下载 Miniconda（轻量版 Anaconda）：**
   ```bash
   wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
   ```

2. **安装 Miniconda：**
   ```bash
   bash Miniconda3-latest-Linux-x86_64.sh
   ```

3. **初始化 Conda（如果需要的话）：**
   ```bash
   source ~/.bashrc
   ```

4. **创建并激活数据分析环境（Python 3.10）：**
   ```bash
   conda create -n data_analysis python=3.10 -y
   conda activate data_analysis
   ```

5. **安装必要的包：**
   ```bash
   conda install jupyter numpy pandas matplotlib seaborn -y
   ```

6. **启动 Jupyter Notebook：**

   ```bash
   jupyter notebook
   ```

---

### 0.2 无 Linux 环境同学：使用 Google Colab

- 访问 [Google Colab](https://colab.research.google.com/)
- 点击【新建笔记本】
- Colab 默认已预装 NumPy 和 Pandas

In [1]:
import numpy as np
import pandas as pd

print("NumPy版本：", np.__version__)
print("Pandas版本：", pd.__version__)

NumPy版本： 2.0.1
Pandas版本： 2.2.3


## Part 1. 什么是 NumPy？

### ✨ NumPy 简介

NumPy（**Numerical Python**）是 Python 语言中专门用于**科学计算**的基础库。  
它主要提供了以下两大核心能力：

- 高效、灵活的**多维数组对象**（`ndarray`）
- 丰富、优化良好的**数组操作函数**（如数学运算、线性代数、傅里叶变换等）

NumPy 通过将底层数据结构和计算过程用 **C 语言**实现，大幅度提升了 Python 处理大规模数据时的速度和效率。  
它是**数据科学**、**机器学习**、**科学工程计算**领域中不可或缺的重要工具。

---

### 🎯 为什么要学习 NumPy？

- 🚀 **速度快**
  - NumPy 底层基于 C 语言实现，直接操作内存，避免了 Python 自身的循环开销。
  - 在处理大量数据时，速度比原生 Python 快几十倍甚至上百倍。

- 🛠️ **功能强大**
  - 支持高维数组（矩阵、张量等）的高效运算。
  - 提供线性代数、傅里叶变换、随机数生成、统计分析等一整套科学计算工具。

- 🔗 **生态基础**
  - 是 Python 科学计算生态系统的**核心基石**。
  - 被 Pandas（数据分析）、Matplotlib（绘图库）、Scikit-learn（机器学习）、TensorFlow（深度学习）等众多流行库广泛依赖和构建在其之上。

- 📚 **学习曲线友好**
  - 相比直接使用 C、C++ 进行数值计算，NumPy 保持了 Python 简洁易读的特点，非常适合快速开发与实验。

---

### 📈 NumPy 能做什么？

- 执行大规模矩阵运算与广播（Broadcasting）
- 快速处理高维数组数据
- 执行复杂的数学、统计、线性代数运算
- 支持数据预处理（归一化、标准化等）
- 在机器学习、深度学习中作为数据流处理的基础

## Part 2. NumPy 数组基础

### 2.1 创建数组

在 NumPy 中，数组（`ndarray`）是用于存储数据的核心对象。它比 Python 内置的列表更加高效，能够支持快速的数学运算和操作。创建数组是学习 NumPy 的第一步。

#### 常用的数组创建方法：

1. **np.array()**：用来从 Python 列表或元组创建数组。
2. **np.zeros()**：创建一个全零数组，通常用于初始化。
3. **np.ones()**：创建一个全一数组，适用于初始化所有元素值为 1 的场景。
4. **np.arange()**：生成一个均匀分布的数值数组，类似于 Python 中的 `range()`，但返回的是 NumPy 数组。
5. **np.linspace()**：生成一个等差数列的数组，用于生成固定区间内的等间隔数值。
6. **np.random()**：生成随机数组，包含各种随机数生成函数，如 `np.random.rand()`、`np.random.randn()` 等。

In [2]:
# 使用 np.array 创建数组
arr1 = np.array([1, 2, 3, 4, 5, 6])
print("使用 np.array 创建一维数组：", arr1)

# 使用 np.zeros 创建全零数组
zeros = np.zeros((2, 3))  # 创建一个 2 行 3 列的全零数组
print("使用 np.zeros 创建全零数组：\n", zeros)

# 使用 np.ones 创建全一数组
ones = np.ones((3, 4))  # 创建一个 3 行 4 列的全一数组
print("使用 np.ones 创建全一数组：\n", ones)

# 使用 np.arange 创建等差数列数组
arange_arr = np.arange(0, 10, 2)  # 从 0 到 10 步长为 2
print("使用 np.arange 创建等差数列数组：", arange_arr)

# 使用 np.linspace 创建等间隔数组
linspace_arr = np.linspace(0, 10, 5)  # 在 0 到 10 之间创建 5 个等间隔的数
print("使用 np.linspace 创建等间隔数组：", linspace_arr)

# 使用 np.random 创建随机数组
random_arr = np.random.rand(2, 3)  # 生成一个 2 行 3 列的随机数数组（0到1之间）
print("使用 np.random 创建随机数组：\n", random_arr)

使用 np.array 创建一维数组： [1 2 3 4 5 6]
使用 np.zeros 创建全零数组：
 [[0. 0. 0.]
 [0. 0. 0.]]
使用 np.ones 创建全一数组：
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
使用 np.arange 创建等差数列数组： [0 2 4 6 8]
使用 np.linspace 创建等间隔数组： [ 0.   2.5  5.   7.5 10. ]
使用 np.random 创建随机数组：
 [[0.84307235 0.2154388  0.48736293]
 [0.8058693  0.61835349 0.3383395 ]]


### 2.2 数组基本属性

在 NumPy 中，数组不仅仅是数据的容器，每个数组都有一些基本属性，用于描述它的形状、大小和数据类型等信息。通过这些属性，我们可以更方便地了解数组的结构和特点。

#### 主要的数组基本属性：

1. **`shape`**：返回数组的维度信息，表示数组在各个轴上的大小。对于二维数组，返回的是 `(行数, 列数)`，对于三维数组，返回 `(深度, 行数, 列数)`，以此类推。
2. **`size`**：返回数组中所有元素的总个数。即数组的总元素数。
3. **`dtype`**：返回数组中元素的数据类型。NumPy 支持多种数据类型，如 `int32`、`float64` 等。

In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

# 获取数组的维度信息
print("数组维度 (shape)：", arr.shape)

# 获取数组元素的总个数
print("数组元素个数 (size)：", arr.size)

# 获取数组元素的数据类型
print("数组数据类型 (dtype)：", arr.dtype)

数组维度 (shape)： (2, 3)
数组元素个数 (size)： 6
数组数据类型 (dtype)： int64


## Part 3. 数组索引与切片

在 NumPy 中，我们可以使用**索引**和**切片**来高效地访问和操作数组中的元素。这些操作是数据分析和处理过程中必不可少的工具。

#### 数组索引操作：

- **单元素索引**：通过索引可以访问数组中的单个元素。对于一维数组，通过单个索引获取元素；对于多维数组，使用逗号分隔的索引来访问不同维度的元素。
- **负索引**：与 Python 列表类似，NumPy 数组也支持负索引，表示从数组的末尾开始访问元素。`-1`表示最后一个元素，`-2`表示倒数第二个元素，以此类推。

#### 数组切片操作：

- **基本切片**：通过切片操作符（`:`）来选择数组的子集，类似于 Python 中的列表切片。可以指定开始、结束和步长参数。
- **多维数组切片**：在多维数组中，可以为每个维度指定切片，通过逗号分隔多个切片操作。

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 访问单个元素（二维数组中的元素）
# 访问第二行第三列的元素
print("第二行第三列元素：", arr[1, 2]) 

# 使用负索引访问元素（倒数第二行倒数第一列的元素）
print("倒数第二行倒数第一列元素：", arr[-2, -1])

# 切片操作
# 获取第一行的所有元素
print("第一行：", arr[0, :])

# 获取第一列的所有元素
print("第一列：", arr[:, 0])

# 获取前两行前两列的子数组
print("前两行前两列子数组：\n", arr[:2, :2])

# 获取最后两行最后两列的子数组
print("最后两行最后两列子数组：\n", arr[-2:, -2:])

# 使用步长进行切片（获取每行中的偶数列）
print("每行的偶数列：\n", arr[:, ::2])

第二行第三列元素： 6
倒数第二行倒数第一列元素： 6
第一行： [1 2 3]
第一列： [1 4 7]
前两行前两列子数组：
 [[1 2]
 [4 5]]
最后两行最后两列子数组：
 [[5 6]
 [8 9]]
每行的偶数列：
 [[1 3]
 [4 6]
 [7 9]]


## Part 4. 数组运算与统计

NumPy 不仅仅支持基本的数组操作，还提供了强大的数组运算和统计功能。这些功能允许我们在数组上执行数学运算、聚合操作以及计算各种统计量，极大地提升了数据处理和分析的效率。

#### 数组运算

NumPy 数组支持向量化运算，这意味着我们可以直接对数组进行数学运算，而无需显式的循环结构。这使得操作大规模数据集时非常高效。

1. **数组加法**：通过 `+` 操作符可以直接进行数组元素的逐元素加法。
2. **数组乘法**：通过 `*` 操作符可以进行逐元素的乘法运算。

#### 数组统计

NumPy 还提供了丰富的统计函数，可以方便地计算数组的各种统计量：

1. **求和**：`np.sum()` 用于计算数组中所有元素的总和。
2. **均值**：`np.mean()` 计算数组元素的算术平均值。
3. **最大值与最小值**：`np.max()` 和 `np.min()` 分别返回数组中的最大值和最小值。
4. **标准差**：`np.std()` 计算数组的标准差，衡量数据的离散程度。

这些统计函数常用于数据分析和数据预处理阶段，帮助我们快速了解数据的分布和特征。

In [5]:
# 创建两个一维数组
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# 数组加法：逐元素加法
print("数组加法：", arr1 + arr2)

# 数组乘法：逐元素乘法
print("数组乘法：", arr1 * arr2)

# 求和：计算数组所有元素的总和
print("求和：", np.sum(arr1))

# 均值：计算数组元素的平均值
print("均值：", np.mean(arr1))

# 最大值：返回数组中的最大值
print("最大值：", np.max(arr1))

# 最小值：返回数组中的最小值
print("最小值：", np.min(arr1))

# 标准差：计算数组元素的标准差
print("标准差：", np.std(arr1))

数组加法： [6 6 6 6 6]
数组乘法： [5 8 9 8 5]
求和： 15
均值： 3.0
最大值： 5
最小值： 1
标准差： 1.4142135623730951


## Part 5. NumPy常见高级功能

### 5.1 广播机制（Broadcasting）

广播机制（**Broadcasting**）是 NumPy 中的一项强大功能，它允许形状不同的数组之间进行数学运算，而无需显式地调整数组的维度。通过自动扩展较小数组的形状，使其能够与较大数组进行元素级别的操作，从而实现高效的计算。

广播机制在 NumPy 中的应用非常广泛，尤其是在处理大规模数据时，它可以大大提升计算性能，避免了手动调整数组形状的复杂性。

#### 广播规则：

广播机制遵循一定的规则来判断两个数组是否可以进行广播运算：

1. **规则一**：如果两个数组的维度数不同，那么小维度数组的形状会在最左边补上 `1`，直到两个数组的维度数相同。
2. **规则二**：如果两个数组在某一维度上的长度不同，且其中一个数组在该维度上的长度为 `1`，则该数组在该维度上会被“广播”以匹配另一个数组的形状。
3. **规则三**：如果两个数组在任何维度上的长度都不相同，且都不为 `1`，则无法进行广播运算。

这些规则确保了 NumPy 可以在不需要显式复制数据的情况下，自动将数组扩展为兼容的形状，避免了内存的浪费。

In [6]:
# 创建两个数组：A 是一维数组，B 是二维数组
A = np.array([1, 2, 3])  # 形状 (3,) -> (1,3) -> (3,3)
B = np.array([[10], [20], [30]])  # 形状 (3, 1) -> (3,3)

# 广播加法：A 的形状是 (3,)，B 的形状是 (3, 1)，广播后可以相加
print("广播加法结果：\n", A + B)

广播加法结果：
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


### 5.2 布尔索引与条件筛选

布尔索引（Boolean Indexing）是 NumPy 中的一项强大功能，允许通过条件表达式直接从数组中筛选出满足特定条件的元素。相比传统的循环遍历方式，布尔索引更加简洁和高效，尤其在处理大规模数据时，能够显著提高代码的运行速度。

通过布尔索引，我们可以根据数组元素的值或其他条件，快速提取符合要求的数据子集。布尔索引的基础是创建一个布尔类型的数组，它的每个元素对应原数组中元素是否满足条件，最后通过该布尔数组来索引原数组。

#### 布尔索引的应用：

1. **条件筛选**：通过条件表达式，例如 `arr > 25`，生成一个布尔数组，表示哪些元素满足条件。
2. **多重条件筛选**：可以通过 `&`（与）和 `|`（或）运算符将多个条件结合使用，进行更复杂的筛选。

布尔索引不仅可以用于一维数组，也可以用于多维数组，在数据分析和处理任务中广泛使用。

In [7]:
# 创建一个一维数组
arr = np.array([10, 20, 30, 40, 50])

# 布尔索引：筛选出大于25的元素
print("大于25的元素：", arr[arr > 25])

大于25的元素： [30 40 50]


## Part 6. 数组拼接与拆分

在数据处理过程中，有时我们需要将多个数组合并在一起，或者将一个数组拆分成多个小数组。NumPy 提供了非常灵活的函数来完成这些操作，包括水平拼接、垂直拼接、等量拆分等功能。

数组拼接常用于数据集的合并或扩展，而数组拆分则在数据划分、数据增强等任务中非常有用。


### 6.1 数组拼接

数组拼接是将多个数组沿着某个指定的轴连接成一个新的数组。NumPy 提供了几个拼接函数，其中最常用的是 `np.concatenate()`。通过该函数，我们可以沿着不同的轴（如行或列）拼接数组。

#### 常见的拼接方式：

1. **一维数组拼接**：将多个一维数组拼接成一个长的一维数组。
2. **二维数组按行拼接**：沿着垂直方向（行）将多个二维数组拼接。
3. **二维数组按列拼接**：沿着水平方向（列）将多个二维数组拼接。

通过改变 `axis` 参数，`np.concatenate()` 可以控制拼接的方向（按行拼接或按列拼接）。

In [8]:
# 使用np.concatenate拼接数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concat_arr = np.concatenate([arr1, arr2])
print("一维数组拼接结果：", concat_arr)

# 在二维数组上按行（axis=0）拼接
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6]])
concat_arr2 = np.concatenate([arr3, arr4], axis=0)
print("二维数组按行拼接：\n", concat_arr2)

一维数组拼接结果： [1 2 3 4 5 6]
二维数组按行拼接：
 [[1 2]
 [3 4]
 [5 6]]


### 6.2 数组拆分

数组拆分（Splitting）是将一个大的数组分割成多个小数组的操作。在数据处理中，拆分操作常用于将数据集划分为训练集、测试集，或者进行批处理等任务。

NumPy 提供了灵活的数组拆分函数，常用的是 `np.split()`，可以根据指定的数量或位置将数组平均或指定位置切分成多个子数组。

#### 常见的拆分方式：

1. **平均拆分**：将数组均匀地分成若干个子数组，要求总元素个数可以被拆分的部分整除。
2. **按指定位置拆分**：可以通过指定分割索引的位置，自定义数组的切分点。

In [9]:
# 创建一个一维数组
arr5 = np.arange(10)
print("原数组：", arr5)

# 1. 使用 np.split 平均拆分成两部分
split_arr1 = np.split(arr5, 2)
print("\n使用 np.split 平均拆分成两部分：")
for idx, part in enumerate(split_arr1):
    print(f"部分 {idx+1}:", part)

# 2. 使用 np.split 按指定位置拆分
# 在索引 3 和 7 处分割，得到三段：[0,1,2], [3,4,5,6], [7,8,9]
split_arr2 = np.split(arr5, [3, 7])
print("\n使用 np.split 指定位置拆分（索引3和7）：")
for idx, part in enumerate(split_arr2):
    print(f"部分 {idx+1}:", part)

# 3. 使用 np.array_split 不等量拆分成3部分
# 可以拆成尽量平均的三部分，即：[0,1,2,3], [4,5,6], [7,8,9]
split_arr3 = np.array_split(arr5, 3)
print("\n使用 np.array_split 不等量拆分成三部分：")
for idx, part in enumerate(split_arr3):
    print(f"部分 {idx+1}:", part)


原数组： [0 1 2 3 4 5 6 7 8 9]

使用 np.split 平均拆分成两部分：
部分 1: [0 1 2 3 4]
部分 2: [5 6 7 8 9]

使用 np.split 指定位置拆分（索引3和7）：
部分 1: [0 1 2]
部分 2: [3 4 5 6]
部分 3: [7 8 9]

使用 np.array_split 不等量拆分成三部分：
部分 1: [0 1 2 3]
部分 2: [4 5 6]
部分 3: [7 8 9]


## Part 7. 矩阵运算基础
NumPy 提供了丰富的线性代数运算接口，支持矩阵乘法、矩阵转置、矩阵求逆等常见操作。这些功能广泛应用于数据科学、机器学习、工程计算等领域，是深入理解矩阵运算的基础。

### 7.1 矩阵乘法（点积）

矩阵乘法（Matrix Multiplication）又称为点积（Dot Product），在 NumPy 中可以使用 `np.dot()` 或 `@` 运算符实现。矩阵乘法不同于对应元素的逐元素乘法，它遵循线性代数中的乘法规则，即第一个矩阵的行与第二个矩阵的列相乘并求和。

矩阵乘法要求两个矩阵的**形状匹配**：第一个矩阵的列数必须等于第二个矩阵的行数，否则无法进行乘法。

In [10]:
# 创建两个二维矩阵
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 使用 np.dot 进行矩阵乘法
matrix_product = np.dot(A, B)
print("使用 np.dot 进行矩阵乘法结果：\n", matrix_product)

# 使用 @ 运算符进行矩阵乘法
matrix_product2 = A @ B
print("\n使用 @ 运算符进行矩阵乘法结果：\n", matrix_product2)

使用 np.dot 进行矩阵乘法结果：
 [[19 22]
 [43 50]]

使用 @ 运算符进行矩阵乘法结果：
 [[19 22]
 [43 50]]


### 7.2 矩阵转置

矩阵转置（Transpose）是线性代数中的基本操作之一，指的是将矩阵的行和列进行交换。  
在 NumPy 中，可以使用 `np.transpose()` 函数或数组对象自带的 `.T` 属性快速完成转置操作。

矩阵转置在实际应用中非常常见，如在求解线性方程组、矩阵分解、特征值分解等操作中都会用到。

In [11]:
A = np.array([[1, 2], [3, 4]])

# 使用 np.transpose 进行矩阵转置
A_T = np.transpose(A)
print("使用 np.transpose 进行矩阵转置：\n", A_T)

# 使用 .T 属性进行矩阵转置
A_T2 = A.T
print("\n使用 .T 属性进行矩阵转置：\n", A_T2)

使用 np.transpose 进行矩阵转置：
 [[1 3]
 [2 4]]

使用 .T 属性进行矩阵转置：
 [[1 3]
 [2 4]]


## Part 8. 课堂练习

### 📚 课堂练习题目

1. **数组基本操作与统计分析**
   
   - 创建一个 **5×5** 的随机整数数组，数值范围在 **1 到 100** 之间；
   - 使用**布尔索引**提取出数组中**所有大于 50** 的元素；
   - 分别计算数组**每一行的均值**和**标准差**；
   - 将该数组**reshape**成一个**一维数组**（共 25 个元素）。

2. **数组拼接与拆分操作**

   - 创建两个大小为 **2×4** 的随机整数数组（范围任意合理，比如 1 到 10）；
   - 将这两个数组**在行方向（axis=0）进行拼接**；
   - 将这两个数组**在列方向（axis=1）进行拼接**；
   - 对其中一个原数组，使用`np.split`**或**`np.array_split`方法将其拆分成两个子数组。

3. **矩阵运算与转置**

   - 创建两个 **2×2** 的矩阵；
   - 计算它们的**矩阵乘积**（使用 `np.dot` 或 `@` 运算符）；
   - 分别求出这两个矩阵的**转置矩阵**。